# lychee.toml
# https://lychee.cli.rs/guides/config/

# サイトのルートディレクトリを指定
root_dir = "./_public"

exclude = [
    # HTTP/2エラーが出るドメイン
    'https://www\.adobe\.com/.*',
    'https://helpx\.adobe\.com/.*',
    'https://www\.autodesk\.com/.*',
    # Googleのfaviconサービス
    'https://www\.google\.com/s2/favicons.*',
    # SamsungのOGP画像（プロトコル相対パス対策）
    '\.*cdn\.samsung\.com/etc/designs/.*',
    # Cloudflareの管理外の画像パス：
    # og:image自体が"/img/cf-social-card.png"になっているので除外する
    '.*/img/cf-social-card\.png'
]

accept = [200, 403, 429]