backend:
  name: github
  repo: homironi/homimemo
  branch: develop
  base_url: https://homimemo-cms-auth.vercel.app
  auth_endpoint: api/auth/begin
  site_domain: homironi.com
  squash_merges: true
  commit_messages:
    create: "[add] {{slug}}"
    update: "[update] {{slug}}"
    delete: "[delete] {{slug}}"
    uploadMedia: "[add] img: {{path}}"
    deleteMedia: "[delete] img: {{path}}"

media_folder: "public/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "記事"
    folder: "_contents/articles"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "下書き", name: "draft", widget: "boolean", default: true, required: true }
      - { label: "公開日時", name: "publishDate", widget: "datetime", required: true }
      - { label: "最終編集日時", name: "lastModDate", widget: "datetime", required: true }
      - { label: "カテゴリー", name: "category", widget: "relation", collection: "categories", search_fields: ["name", "description"], value_field: "name", required: true }
      - { label: "タグ", name: "tags", widget: "relation", collection: "tags", search_fields: ["name", "description"], value_field: "name", multiple: true, required: false }
      - { label: "サムネイル", name: "thumbnail", widget: "image", required: false }
      - { label: "説明", name: "description", widget: "string", required: true }
      - { label: "本文", name: "body", widget: "markdown", required: true }

  - name: "static-articles"
    label: "固定記事"
    folder: "_contents/static-articles"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "下書き", name: "draft", widget: "boolean", default: true, required: true }
      - { label: "公開日時", name: "publishDate", widget: "datetime", required: true }
      - { label: "最終編集日時", name: "lastModDate", widget: "datetime", required: true }
      - { label: "サムネイル", name: "thumbnail", widget: "image", required: false }
      - { label: "説明", name: "description", widget: "string", required: true }
      - { label: "本文", name: "body", widget: "markdown", required: true }

  - name: "categories"
    label: "カテゴリー"
    folder: "_contents/categories"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "カテゴリー名", name: "name", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "1文字以上の英数字もしくはハイフンのみを使用します"] }
      - { label: "説明", name: "description", widget: "string", required: false }

  - name: "tags"
    label: "タグ"
    folder: "_contents/tags"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "タグ名", name: "name", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "1文字以上の英数字もしくはハイフンのみを使用します"] }
      - { label: "説明", name: "description", widget: "string", required: false }