name: Add Missing Article IDs

on:
    workflow_dispatch:
    pull_request:
        paths:
            - "_contents/articles/**.md"
        types: [opened, synchronize]

jobs:
  add-id-and-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # PRにコメントを追加する権限

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run script and save output
        id: run_script
        run: |
          echo "Running script..."
          OUTPUT=$(npm run add:article-id)
          echo "$OUTPUT"
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event.pull_request != null
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment "$PR_URL" --body "## ✏️ 記事IDの付与ログ  
          ${{ steps.run_script.outputs.output }}
          "
