name: Build test

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            # Module CSS の型ファイルを生成して後のビルドでエラーにならないか確認できるようにする
            - name: module css type check
              run: npm run tcm

            - name: Build
              run: npm run build