name: "Chromatic"

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
            - develop
        paths:
          - "src/**.css"
          - "!src/**/page.module.css"
          - "src/components/**"
          - "!src/components/server/**"
          - "src/stories/**"
    push:
      branches:
          - main
          - develop
      paths:
          - "src/**.css"
          - "!src/**/page.module.css"
          - "src/components/**"
          - "!src/components/server/**"
          - "src/stories/**"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
