name: deploy to remote

on:
    workflow_dispatch: # 手動実行トリガー
    # push:
    #     branches:
    #         - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            # - name: Install Eleventy
            #   run: npm install -g @11ty/eleventy

            - name: Build site with Eleventy
              run: npx @11ty/eleventy

            - name: Deploy via rsync
              run: |
                  rsync -auzrv -v -e "ssh -vvv -i ~/.ssh/id_rsa -p ${{ secrets.REMOTE_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" --delete "${{ secrets.SOURCE_DIR }}/" "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DIR }}"
