name: deploy to remote

on:
    workflow_dispatch: # 手動実行トリガー
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate SSH key
              run: |
                  echo "$SSH_PRIVATE_KEY" > key
                  chmod 600 key
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install Eleventy
              run: npm install -g @11ty/eleventy

            - name: Build site with Eleventy
              run: npx @11ty/eleventy

            - name: Debug rsync command
              run: |
                  echo "Source directory: ${{ secrets.SOURCE_DIR }}/"
                  echo "Remote user: ${{ secrets.REMOTE_USER }}"
                  echo "Remote host: ${{ secrets.REMOTE_HOST }}"
                  echo "Remote directory: ${{ secrets.REMOTE_DIR }}/"
                  rsync -auzrvv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }}" --delete ${{ secrets.SOURCE_DIR }}/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DIR }}/
