name: Links

on:
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v6
      
      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "_public --cache"
          fail: false

      - name: Save lychee cache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      - name: Create Issue From File
        # 「リンク切れがあり」かつ「イベントが schedule または workflow_dispatch の場合」のみ実行
        if: |
          steps.lychee.outputs.exit_code != 0 && 
          (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
