name: Prettier PR

on:
    pull_request:
        branches: ["*"]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Get base branch
              id: base_branch_ref
              run: echo "branch=${HEAD_REF#refs/heads/}" >> $GITHUB_OUTPUT
              env:
                  HEAD_REF: ${{ github.head_ref }}

            - name: Get base branch name
              id: base_branch_name
              run: echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install

            - name: Run Prettier
              run: npx prettier --write . --config .prettierrc

            - name: Check for changes
              id: prettier_changes
              run: |
                  if ! git diff-files --quiet; then
                    echo "has_changes=true" >> $GITHUB_OUTPUT
                  fi

            - name: Get current date and time (JST)
              if: steps.prettier_changes.outputs.has_changes == 'true'
              id: date
              run: echo "datetime=$(TZ=Asia/Tokyo date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

            - name: Set git user
              if: steps.prettier_changes.outputs.has_changes == 'true'
              run: |
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git config user.name "GitHub Actions"

            - name: Create branch
              if: steps.prettier_changes.outputs.has_changes == 'true'
              run: git checkout -b ${{ steps.base_branch_name.outputs.branch }}/prettier-format-${{ steps.date.outputs.datetime }}

            - name: Commit changes
              if: steps.prettier_changes.outputs.has_changes == 'true'
              run: |
                  git add .
                  git commit -m "Apply Prettier formatting ${{ steps.date.outputs.datetime }}"
                  git push origin HEAD

            - name: Create Pull Request
              if: steps.prettier_changes.outputs.has_changes == 'true'
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ steps.base_branch_name.outputs.branch }}/prettier-format-${{ steps.date.outputs.datetime }}
                  base: ${{ steps.base_branch_ref.outputs.branch }}
                  title: "Apply Prettier formatting ${{ steps.date.outputs.datetime }}"
                  body: This pull request contains formatting changes applied by Prettier.
