name: Prettier Commit

on:
    pull_request:
        branches: ["*"]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ACCESS_TOKEN_AUTO_COMMIT }}
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0 # 履歴全体を取得するため

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install

            - name: Get changed files
              id: changed-files
              run: |
                  changed_files=$(git diff --name-only --diff-filter=d HEAD~1)
                  echo "files=$changed_files" >> $GITHUB_OUTPUT

            - name: Run Prettier
              if: steps.changed-files.outputs.files
              run: npx prettier --write ${{ steps.changed-files.outputs.files }} --config .prettierrc

            - name: Git Auto Commit
              if: steps.changed-files.outputs.files
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Apply Prettier formatting
                  commit_user_name: GitHub Actions
                  commit_user_email: github-actions[bot]@users.noreply.github.com
                  commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
